test slack notification 001

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -39,6 +39,23 @@ jobs:
       - uses: actions/checkout@v2
       - name: build step
         run: echo "building..."
+      - name: force failure
+        run: exit 1
+#      - uses: 8398a7/action-slack@v3
+#          with:
+#            status: ${{ job.status }}
+#            fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
+#          env:
+#            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
+#          if: always() # Pick up events even if the job fails or is canceled.
+      - name: slack notification
+        if: ${{ failure() }}
+        uses: slackapi/slack-github-action@v1.15.0
+        with:
+          channel-id: 'kata-jenkins'  # Slack channel id to post message
+          slack-message: 'Build failure!'
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
 
   release:
     runs-on: ubuntu-latest
@@ -55,22 +72,24 @@ jobs:
     name: Deploy example
     steps:
       - uses: actions/checkout@v2
-      - name: Run playbook
-        uses: dawidd6/action-ansible-playbook@v2
-        with:
-          playbook: deploy.yml
-          # Optional, directory where playbooks live
-          directory: ${{ env.DEVOPS_DIR }}/ansible/
-          key: ${{secrets.SSH_PRIVATE_KEY}}
-          inventory: |
-            [all]
-            ${{ secrets.REMOTE_HOST }} ansible_user=${{ secrets.REMOTE_USER }}
-          options: |
-            --extra-vars nginx_image="nginx:1.21.3-alpine"
-            --extra-vars backend_image="jjquispeopx/backend"
-            --extra-vars registry_user=${{secrets.REGISTRY_USER}}
-            --extra-vars registry_token=${{secrets.REGISTRY_TOKEN}}
-            --verbose
+      - name: deploy step
+        run: echo "deploying..."
+#      - name: Run playbook
+#        uses: dawidd6/action-ansible-playbook@v2
+#        with:
+#          playbook: deploy.yml
+#          # Optional, directory where playbooks live
+#          directory: ${{ env.DEVOPS_DIR }}/ansible/
+#          key: ${{secrets.SSH_PRIVATE_KEY}}
+#          inventory: |
+#            [all]
+#            ${{ secrets.REMOTE_HOST }} ansible_user=${{ secrets.REMOTE_USER }}
+#          options: |
+#            --extra-vars nginx_image="nginx:1.21.3-alpine"
+#            --extra-vars backend_image="jjquispeopx/backend"
+#            --extra-vars registry_user=${{secrets.REGISTRY_USER}}
+#            --extra-vars registry_token=${{secrets.REGISTRY_TOKEN}}
+#            --verbose
 
 #  example-job:
 #    runs-on: ubuntu-latest
